### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Katreenlooper** [qxcv/pose-prediction#3]
Hey, 
I have trained  LSTM baseline model but when i want to train (deep Markov model) i got the following error,  Although i installed Theano package. Can you please tell me what is the problem?

Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import addpaths  # noqa
  File "/home/kathreen/pose-prediction/structuredinference/expt-ikeadb/addpaths.py", line 12, in <module>
    assert os.path.isdir(path), 'code at %s must exist' % path
AssertionError: code at /home/kattreen/repos/theanomodels must exist

Another question:If i want to visualize the results of LSTM baseline (using results_lstm.h5 instead of results_dkf.h5 ) prediction using the following command, what should i modify further?
cd ~/repos/structuredinference/expt-ikeadb
source activate pose-prediction  # or `workon` or whatever
./make_eval_videos.py  results_lstm.h5  --vid-dir some-dest-dir

Lastly, if i have my own datasets (video.mp4 ) and i want to predict the pose of the human motion in that video, can you tell me what should i do? 

Thank you very much

**Comment by qxcv** [comment]
1. `theanomodels` refers to [this repository](https://github.com/qxcv/theanomodels). You'll have to clone it and then change [addpaths.py](https://github.com/qxcv/pose-prediction/blob/master/structuredinference/common_pp/addpaths.py) to point to the right place.
2. That video command looks fine to me, but it has been four years since I've run any of this. Do you get an error when you try that?
3. Extract the poses with some third-party software (e.g. convolutional pose machines), then feed it into this code using a similar strategy to existing supported datasets. Unfortunately it has been long enough since I've touched this code that I don't remember the precise steps to add new datasets, though.
